# This is a basic workflow to help you get started with Actions

name: CI

# Triggers the workflow on push or pull request events but only for the FS branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Start
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Install node_modules
      - name: install node modules
      - run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: test coverage
        run: npm run test:cov
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKUFOODSECUREBACKEND
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKUFOODSECUREBACKEND
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKUFOODSECUREBACKEND }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Add remote origin to Heroku
        run: git remote add heroku https://heroku:${{ secrets.HEROKUFOODSECUREBACKEND }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      - name: Push to Heroku
        run: git push heroku master
        if: github.ref == 'refs/heads/master'