# This is a basic workflow to help you get started with Actions

name: CI

# Triggers the workflow on push or pull request events but only for the FS branch
on: [push, pull_request]

# .github/workflows/custom-deploy.yml
jobs:
  custom-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKUFOODSECUREBACKEND
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKUFOODSECUREBACKEND
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKUFOODSECUREBACKEND }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Add remote origin to Heroku
        run: git remote add heroku https://heroku:${{ secrets.HEROKUFOODSECUREBACKEND }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      - name: Push to Heroku
        run: git push heroku master
        if: github.ref == 'refs/heads/master'